# Docker image
image: ruby:2.3.0

pipelines:
  default:
    - step:
        script:
          - bundle install
          - bundle exec rake build

  tags:
    '*':
      - step:
         script:
          - bundle install
          - bundle exec rake build
          - test -d ~/.gem || mkdir ~/.gem
          - "echo \":rubygems_api_key: '${RUBYGEM_API_KEY}'\" > ~/.gem/credentials"
          - chmod 600 ~/.gem/credentials
          - bundle exec rake release
